language: node_js
dist: trusty
sudo: false

node_js:
  # Use the explicit NodeJS LTS version 8.9.4 to avoid any automatic upgrade of the version.
  # This ensures that all Travis jobs run consistently and don't have different Node versions.
  - '8.12.0'

addons:
  chrome: stable
  firefox: latest

branches:
  only:
  - master
  # 5.2.x, 6.0.x, etc
  - /\d+\.\d+\.x/
  # 5.x, 6.x, etc
  - /\d+\.x/

jobs:
  include:
    - env: "MODE=saucelabs_required"

env:
  global:
    # Keep Yarn version in sync with Yarn version within Bazel WORKSPACE.
    - YARN_VERSION=1.9.4
    - LOGS_DIR=/tmp/angular-material2-build/logs
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987
    - BROWSER_STACK_USERNAME=angularteam1
    - BROWSER_STACK_ACCESS_KEY=CaXMeMHD9pr5PHg8N7Jq
    - BROWSER_PROVIDER_READY_FILE=/tmp/angular-material2-build/readyfile
    - BROWSER_PROVIDER_ERROR_FILE=/tmp/angular-material2-build/errorfile

before_install:
  - source ./scripts/ci/install-yarn.sh

install:
  - ./scripts/ci/travis-install.sh
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then ./scripts/install-angular-snapshot.sh --only-save; fi

before_script:
  - mkdir -p $LOGS_DIR

script:
  - ./scripts/ci/travis-script.sh

cache:
  yarn: true
  directories:
    - ./node_modules/
